In [1]:
# ===========================
# Setup + Imports
# ===========================
import os, random, numpy as np, pandas as pd
from pathlib import Path

# Config
RANDOM_SEED = 2025
TEST_SIZE   = 0.20
TEXT_COL    = "full_text"
ID_COL      = "essay_id_comp"
GROUP_COL   = "gender"
TARGET_COL  = "holistic_essay_score_3cat"

# Output directory
OUT_DIR = Path("outputs")
OUT_DIR.mkdir(exist_ok=True, parents=True)

# ---------------------------
# Load Cleaned Dataset
# ---------------------------
df = pd.read_csv("./data/persuade_clean.csv")

print(">>> Cleaned dataset loaded")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist(), "\n")

# ---------------------------
# Utility: Reproducibility
# ---------------------------
os.environ["PYTHONHASHSEED"] = str(RANDOM_SEED)
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ---------------------------
# Quick Missing Check
# ---------------------------
print("\n=== Missing Values ===")
print(df[[ID_COL, TEXT_COL, GROUP_COL, TARGET_COL]].isna().sum())

>>> Cleaned dataset loaded
Shape: (2167, 5)
Columns: ['essay_id_comp', 'full_text', 'gender', 'holistic_essay_score', 'holistic_essay_score_3cat']


=== Missing Values ===
essay_id_comp                0
full_text                    0
gender                       0
holistic_essay_score_3cat    0
dtype: int64

In [2]:
# ===========================
# Data Split (80/20 stratified by gender)
# ===========================
from sklearn.model_selection import train_test_split

# Split (preserve gender proportion for fairness checks)
train_df, test_df = train_test_split(
    df,
    test_size=TEST_SIZE,
    random_state=RANDOM_SEED,
    stratify=df[GROUP_COL]
)

# Arrays for downstream use
X_train     = train_df[TEXT_COL].astype(str).str.strip().tolist()
y_train     = train_df[TARGET_COL].to_numpy(dtype=float)
id_train    = train_df[ID_COL].to_numpy()
group_train = train_df[GROUP_COL].to_numpy()

X_test      = test_df[TEXT_COL].astype(str).str.strip().tolist()
y_test      = test_df[TARGET_COL].to_numpy(dtype=float)
id_test     = test_df[ID_COL].to_numpy()
group_test  = test_df[GROUP_COL].to_numpy()

# Quick summary
print(">>> Data split complete")
print(f"Train size: {len(train_df):,} | Test size: {len(test_df):,}")
print("\nGender distribution (train):")
print(train_df[GROUP_COL].value_counts(normalize=True).sort_index().round(3))
print("\nGender distribution (test):")
print(test_df[GROUP_COL].value_counts(normalize=True).sort_index().round(3))

>>> Data split complete
Train size: 1,733 | Test size: 434

Gender distribution (train):
gender
F    0.474
M    0.526
Name: proportion, dtype: float64

Gender distribution (test):
gender
F    0.475
M    0.525
Name: proportion, dtype: float64

In [3]:
# Save train/test splits for later bias analysis
train_df.to_csv(OUT_DIR / "train_split.csv", index=False)
test_df.to_csv(OUT_DIR / "test_split.csv", index=False)

In [ ]:
# # ===========================
# # Optional Check Block
# # ===========================
# print("\n=== Secret check: train set ===")
# print("Counts:")
# print(train_df.groupby(GROUP_COL)[TARGET_COL].value_counts().unstack(fill_value=0))
# print("\nProportions:")
# print(train_df.groupby(GROUP_COL)[TARGET_COL].value_counts(normalize=True).unstack().round(3))

# print("\n=== Secret check: test set ===")
# print("Counts:")
# print(test_df.groupby(GROUP_COL)[TARGET_COL].value_counts().unstack(fill_value=0))
# print("\nProportions:")
# print(test_df.groupby(GROUP_COL)[TARGET_COL].value_counts(normalize=True).unstack().round(3))

In [6]:
# ===========================
# TF-IDF + Ordinal Logistic (PO) with 5-fold CV
# ===========================
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import (
    mean_absolute_error, make_scorer, cohen_kappa_score
)
import pandas as pd
import numpy as np
import joblib

# Ordinal logistic regression (proportional-odds) — sklearn-compatible
try:
    import mord  # pip install mord
except ImportError as e:
    raise SystemExit(
        "The 'mord' package is required for ordinal logistic regression.\n"
        "Install with: pip install mord"
    )

# Ensure y are integer class labels {1,2,3}
y_train_ord = y_train.astype(int)
y_test_ord  = y_test.astype(int)

# Stratified 5-fold CV
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)

# Pipeline: TF-IDF -> Ordinal Logistic
pipe = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("ord", mord.LogisticAT(alpha=1.0))  # alpha = L2 reg strength
])

# Hyperparameter grid
param_grid = {
    "tfidf__ngram_range": [(1,1), (1,2)],
    "tfidf__min_df": [1, 3, 5],
    "tfidf__max_df": [0.85, 0.90, 0.95],
    "tfidf__max_features": [10_000, 20_000, 50_000],
    "ord__alpha": [0.0, 1e-3, 1e-2, 1e-1, 1.0]
}

# Use MAE as the CV scoring metric
grid = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    scoring=make_scorer(mean_absolute_error, greater_is_better=False),
    cv=cv,
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

# Fit on training data
grid.fit(X_train, y_train_ord)

# Inspect CV results
print("\n>>> Cross-Validation summary (best on MAE)")
print("Best params:", grid.best_params_)
print(f"Best CV MAE: {-grid.best_score_:.4f}")

# Save CV results
cv_df = pd.DataFrame(grid.cv_results_)
cv_df_sorted = cv_df.sort_values("mean_test_score", ascending=False)
cv_path = OUT_DIR / "cv_results_tfidf_ordlogit.csv"
cv_df_sorted.to_csv(cv_path, index=False)
print(f"Saved CV results: {cv_path}")

# Use best estimator for test predictions
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test).astype(int)

# Save model and predictions
model_path = OUT_DIR / "model_tfidf_ordlogit_cv.joblib"
joblib.dump(best_model, model_path)

preds_path = OUT_DIR / "scores_tfidf_ordlogit_cv.csv"
pd.DataFrame({
    ID_COL: id_test,
    GROUP_COL: group_test,
    "y_true": y_test_ord,
    "y_pred_tfidf_ordlogit_cv": y_pred
}).to_csv(preds_path, index=False)

# Final held-out test metrics
mae = mean_absolute_error(y_test_ord, y_pred)
qwk = cohen_kappa_score(y_test_ord, y_pred, weights="quadratic")

print("\n>>> Held-out Test Results (TF-IDF + Ordinal Logistic)")
print(f"MAE: {mae:.4f}")
print(f"QWK: {qwk:.4f}")
print(f"Saved model: {model_path}")
print(f"Saved predictions: {preds_path}")

Fitting 5 folds for each of 270 candidates, totalling 1350 fits

>>> Cross-Validation summary (best on MAE)
Best params: {'ord__alpha': 0.0, 'tfidf__max_df': 0.95, 'tfidf__max_features': 20000, 'tfidf__min_df': 3, 'tfidf__ngram_range': (1, 2)}
Best CV MAE: 0.2251
Saved CV results: outputs\cv_results_tfidf_ordlogit.csv

>>> Held-out Test Results (TF-IDF + Ordinal Logistic)
MAE: 0.2166
QWK: 0.7098
Saved model: outputs\model_tfidf_ordlogit_cv.joblib
Saved predictions: outputs\scores_tfidf_ordlogit_cv.csv

In [13]:
# ======================================================
# BERT (3-class ordinal) — reuse TF-IDF split, no reloading
# HP search on QWK + MAE, final train on TRAIN+VAL, test once
# ======================================================

import os, gc, itertools, numpy as np, pandas as pd, torch
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import cohen_kappa_score, mean_absolute_error
from transformers import (
    AutoTokenizer, DataCollatorWithPadding,
    AutoModelForSequenceClassification,
    TrainingArguments, Trainer, EarlyStoppingCallback
)

# ---------------------------
# Essentials (defaults if missing)
# ---------------------------
OUT_DIR = OUT_DIR if 'OUT_DIR' in globals() else Path("outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)
SEED = RANDOM_SEED if 'RANDOM_SEED' in globals() else 2025
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BERT_MODEL = globals().get("BERT_MODEL", "bert-base-uncased")

# Reproducibility
os.environ["PYTHONHASHSEED"] = str(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if DEVICE == "cuda":
    torch.cuda.manual_seed_all(SEED)

# ---------------------------
# Use existing split (from TF-IDF code)
# X_train, y_train, X_test, y_test, id_test, group_test must exist
# Make a validation split from X_train/y_train (stratify by labels)
# ---------------------------
assert all(v in globals() for v in ["X_train", "y_train", "X_test", "y_test"]), \
    "Expected X_train, y_train, X_test, y_test from your TF-IDF split."

X_tr, X_val, y_tr, y_val = train_test_split(
    np.array(list(X_train)), np.array(y_train, dtype=int),
    test_size=0.20, random_state=SEED, stratify=np.array(y_train, dtype=int)
)

# ---------------------------
# Tokenizer / Collator / Datasets
# ---------------------------
tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL, use_fast=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def tokenize_texts(texts, max_length=512):
    return tokenizer(
        list(texts), padding=True, truncation=True,
        max_length=max_length, return_attention_mask=True
    )

class EssayDataset(torch.utils.data.Dataset):
    # labels_idx must be 0..2
    def __init__(self, encodings, labels_idx):
        self.encodings = encodings
        self.labels = labels_idx
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

enc_tr  = tokenize_texts(X_tr)
enc_val = tokenize_texts(X_val)
enc_te  = tokenize_texts(X_test)

y_tr_idx  = (np.array(y_tr,  dtype=int) - 1).tolist()
y_val_idx = (np.array(y_val, dtype=int) - 1).tolist()
y_te_idx  = (np.array(y_test, dtype=int) - 1).tolist()

ds_tr   = EssayDataset(enc_tr,  y_tr_idx)
ds_val  = EssayDataset(enc_val, y_val_idx)
ds_test = EssayDataset(enc_te,  y_te_idx)

# ---------------------------
# Metrics: primary QWK, also MAE
# ---------------------------
def compute_metrics(eval_pred):
    logits, labels_idx = eval_pred
    y_pred = logits.argmax(axis=1) + 1  # 1..3
    y_true = labels_idx + 1             # 1..3
    qwk = cohen_kappa_score(y_true, y_pred, weights="quadratic")
    mae = mean_absolute_error(y_true, y_pred)
    return {"qwk": qwk, "MAE": mae}

# ---------------------------
# Model builder
# ---------------------------
def build_model():
    m = AutoModelForSequenceClassification.from_pretrained(BERT_MODEL, num_labels=3)
    m.config.problem_type = "single_label_classification"  # softmax CE for 3 classes
    return m.to(DEVICE)

# ---------------------------
# One config
# ---------------------------
def run_one_config(lr, epochs, batch_size):
    model = build_model()
    args = TrainingArguments(
        output_dir=str(OUT_DIR / f"bert_tune_lr{lr}_bs{batch_size}_ep{epochs}"),
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=epochs,
        learning_rate=lr,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_qwk",
        greater_is_better=True,
        save_total_limit=1,
        logging_steps=50,
        seed=SEED,
        report_to="none",
        fp16=(DEVICE == "cuda"),
    )
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tr,
        eval_dataset=ds_val,
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
    )
    trainer.train()
    eval_out = trainer.evaluate(ds_val)
    del model, trainer
    gc.collect()
    if DEVICE == "cuda": torch.cuda.empty_cache()
    return {
        "lr": lr, "epochs": epochs, "batch_size": batch_size,
        "val_qwk": float(eval_out.get("eval_qwk", np.nan)),
        "val_MAE": float(eval_out.get("eval_MAE", np.inf)),
    }

# ---------------------------
# HP search (incremental CSV; best by QWK then MAE)
# ---------------------------
HP_CSV = OUT_DIR / "bert_hparam_search.csv"
LR_GRID, EPOCHS_GRID, BATCH_GRID = [2e-5, 3e-5, 5e-5], [3, 4], [8, 16]

if HP_CSV.exists():
    hp_df = pd.read_csv(HP_CSV)
    hp_df = hp_df.dropna(subset=["val_qwk", "val_MAE"])
    hp_df = hp_df[np.isfinite(hp_df["val_MAE"])]
    if hp_df.empty:
        print("HP CSV exists but invalid — rerunning search…")
        os.remove(HP_CSV)

if not HP_CSV.exists():
    print("No hyperparam CSV found. Running search…")
    rows = []
    for lr, ep, bs in itertools.product(LR_GRID, EPOCHS_GRID, BATCH_GRID):
        try:
            res = run_one_config(lr, ep, bs)
        except Exception as e:
            print(f"  ⚠️ failed: lr={lr}, ep={ep}, bs={bs}: {e}")
            res = {"lr": lr, "epochs": ep, "batch_size": bs, "val_qwk": np.nan, "val_MAE": np.inf}
        rows.append(res)
        pd.DataFrame(rows).to_csv(HP_CSV, index=False)
        print(f"  tuned → lr={lr}, ep={ep}, bs={bs} | QWK={res['val_qwk']:.4f} | MAE={res['val_MAE']:.4f}")

hp_df = pd.read_csv(HP_CSV)
hp_df = hp_df.dropna(subset=["val_qwk", "val_MAE"])
hp_df = hp_df[np.isfinite(hp_df["val_MAE"])]
hp_df = hp_df.sort_values(["val_qwk", "val_MAE"], ascending=[False, True])
if hp_df.empty:
    raise RuntimeError("HP search produced no valid rows — check compute_metrics and splits.")
best = hp_df.iloc[0].to_dict()
print("\n>>> Best HP config (from CSV)")
print(best, "\n")

best_lr = float(best["lr"])
best_ep = int(best["epochs"])
best_bs = int(best["batch_size"])

# ---------------------------
# Final train on TRAIN+VAL (no eval mid-train), then TEST
# ---------------------------
# Merge TRAIN + VAL
enc_trval = tokenize_texts(np.concatenate([X_tr, X_val]))
y_trval_idx = (np.concatenate([y_tr, y_val]).astype(int) - 1).tolist()
ds_trval = EssayDataset(enc_trval, y_trval_idx)

model = build_model()
final_args = TrainingArguments(
    output_dir=str(OUT_DIR / "bert_final"),
    per_device_train_batch_size=best_bs,
    per_device_eval_batch_size=best_bs,
    num_train_epochs=best_ep,
    learning_rate=best_lr,
    eval_strategy="no",
    save_strategy="no",
    logging_steps=100,
    seed=SEED,
    report_to="none",
    fp16=(DEVICE == "cuda"),
)
final_trainer = Trainer(
    model=model,
    args=final_args,
    train_dataset=ds_trval,
    tokenizer=tokenizer,
    data_collator=data_collator
)
final_trainer.train()

# TEST predictions
pred_out = final_trainer.predict(ds_test)
y_pred_labels = pred_out.predictions.argmax(axis=1) + 1  # back to 1..3

# Save artifacts + predictions
(OUT_DIR / "model_bert").mkdir(exist_ok=True, parents=True)
model.save_pretrained(OUT_DIR / "model_bert")
tokenizer.save_pretrained(OUT_DIR / "tokenizer_bert")

preds_path = OUT_DIR / "scores_bert_ord.csv"
pd.DataFrame({
    "essay_id_comp": id_test,
    "gender": group_test,
    "y_true": np.array(y_test, dtype=int),
    "y_pred_bert": y_pred_labels.astype(int)
}).to_csv(preds_path, index=False)

# Final held-out metrics
qwk = cohen_kappa_score(np.array(y_test, dtype=int), y_pred_labels.astype(int), weights="quadratic")
mae = mean_absolute_error(np.array(y_test, dtype=int), y_pred_labels.astype(int))
print("\n>>> Held-out Test Results (BERT 3-class ordinal) <<<")
print(f"QWK: {qwk:.4f} | MAE: {mae:.4f}")
print(f"Saved hyperparam search: {HP_CSV}")
print(f"Saved predictions: {preds_path}")
print(f"Saved model to: {OUT_DIR / 'model_bert'}")

HP CSV exists but invalid — rerunning search…
No hyperparam CSV found. Running search…

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=2e-05, ep=3, bs=8 | QWK=0.8247 | MAE=0.1383

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=2e-05, ep=3, bs=16 | QWK=0.7929 | MAE=0.1556

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=2e-05, ep=4, bs=8 | QWK=0.8019 | MAE=0.1585

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=2e-05, ep=4, bs=16 | QWK=0.7071 | MAE=0.1844

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  tuned → lr=3e-05, ep=3, bs=8 | QWK=0.8021 | MAE=0.1527

C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=3e-05, ep=3, bs=16 | QWK=0.8166 | MAE=0.1412

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=3e-05, ep=4, bs=8 | QWK=0.7932 | MAE=0.1556

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=3e-05, ep=4, bs=16 | QWK=0.7908 | MAE=0.1671

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=5e-05, ep=3, bs=8 | QWK=0.8184 | MAE=0.1441

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=5e-05, ep=3, bs=16 | QWK=0.8094 | MAE=0.1499

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=5e-05, ep=4, bs=8 | QWK=0.7865 | MAE=0.1643

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:121: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

  tuned → lr=5e-05, ep=4, bs=16 | QWK=0.7804 | MAE=0.1729

>>> Best HP config (from CSV)
{'lr': 2e-05, 'epochs': 3.0, 'batch_size': 8.0, 'val_qwk': 0.8247327216095631, 'val_MAE': 0.138328530259366}

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\max19\AppData\Local\Temp\ipykernel_42684\3519036840.py:205: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  final_trainer = Trainer(

>>> Held-out Test Results (BERT 3-class ordinal) <<<
QWK: 0.7918 | MAE: 0.1636
Saved hyperparam search: outputs\bert_hparam_search.csv
Saved predictions: outputs\scores_bert_ord.csv
Saved model to: outputs\model_bert

In [15]:
os.environ["OPENAI_API_KEY"] ="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"

In [ ]:
# ===========================
# ChatGPT Zeroshot Scorer (1–3, score only, all rows)
# ===========================

import json
import pandas as pd
from openai import OpenAI

client = OpenAI()
MODEL = "gpt-4o-mini"

# SAT-style holistic rubric (1–3). Keep concise so the model latches onto anchors.
RUBRIC_1_TO_3 = (
    "Holistic 1–3 scale for a source-based persuasive essay.\n\n"
    "3: An essay in this category demonstrates clear and consistent mastery. It effectively develops a point of view "
    "with strong and accurate use of source evidence. The essay is well organized and focused, showing coherence and "
    "smooth progression of ideas. Language use is precise, varied, and appropriate, with meaningful sentence variety. "
    "Only minor or occasional errors may appear, but they do not interfere with meaning.\n\n"
    "2: An essay in this category demonstrates adequate but uneven command. It develops a point of view and shows some "
    "critical thinking, though examples and evidence may be limited or inconsistently used. Organization is generally clear, "
    "but lapses in focus or coherence are present. Language is ordinary or inconsistent, sometimes weak or inappropriate in word "
    "choice, and sentence variety may be limited. Noticeable errors in grammar, usage, or mechanics occur, though meaning is "
    "still understandable overall.\n\n"
    "1: An essay in this category demonstrates very limited or no mastery. The point of view may be vague, seriously limited, "
    "or entirely absent, with weak, irrelevant, or no use of evidence. The essay is disorganized or incoherent, with poor focus "
    "and progression of ideas. Vocabulary is very limited or incorrect, sentence structure is severely flawed, and pervasive "
    "errors in grammar, usage, or mechanics interfere with meaning."
)

# Tool forcing: we *only* accept a structured score {1,2,3}
TOOLS = [{
    "type": "function",
    "function": {
        "name": "submit_score",
        "parameters": {
            "type": "object",
            "properties": {
                "score": {"type": "integer", "enum": [1, 2, 3]}
            },
            "required": ["score"],
            "additionalProperties": False
        }
    }
}]

# --- System prompt: criteria-first checklist, analysis->decision pattern (per Xue-style prompt design).
SYSTEM_MSG = (
    "You are an essay rater following the Rubric. "
    "Think step-by-step before deciding, and return the final score.\n\n"
    f"Rubric:\n{RUBRIC_1_TO_3}"
)

def _clean_text(x):
    if x is None:
        return ""
    try:
        if isinstance(x, float) and pd.isna(x):
            return ""
    except Exception:
        pass
    return str(x)

def score_one(essay_id: str, text: str) -> int:
    """
    Score a single essay to {1,2,3} with forced function-call output.
    Internally encourages step-by-step analysis, but only the final score is returned.
    """
    text = _clean_text(text)

    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0,               # reduce randomness
        max_tokens=32,               # we only need the function call
        messages=[
            {"role": "system", "content": SYSTEM_MSG},
            {
                "role": "user",
                "content": (
                    "Rate the following essay on the 1–3 rubric. "
                    "Return only the final score.\n\n"
                    f"ESSAY START:\n\n{text}\nESSAY END"
                )
            },
        ],
        tools=TOOLS,
        tool_choice={"type": "function", "function": {"name": "submit_score"}},  # force function call
    )

    tool_call = resp.choices[0].message.tool_calls[0]
    args = json.loads(tool_call.function.arguments)
    return int(args["score"])

def score_dataframe(df: pd.DataFrame,
                    id_col: str = "essay_id_comp",
                    text_col: str = "full_text",
                    n_cases: int | None = None) -> pd.DataFrame:
    """
    Score all rows (or the first n_cases for a quick pass).
    Retries up to 3 times if a score is missing.
    Returns a DataFrame with [id_col, 'gpt_score'].
    """
    df_use = df if n_cases is None else df.head(int(n_cases))
    out = []

    for _, r in df_use.iterrows():
        essay_id = str(r[id_col])
        text = r[text_col]

        score = None
        for attempt in range(3):  # try up to 3 times
            try:
                score = score_one(essay_id, text)
            except Exception:
                score = None
            if score is not None:
                break
        if score is None:
            print(f"⚠️ Warning: could not score essay_id={essay_id} after 3 attempts")

        out.append({id_col: essay_id, "gpt_score": score})

    return pd.DataFrame(out)

In [60]:
# ===========================
# Quick sanity check (10 essays only)
# ===========================
from sklearn.metrics import cohen_kappa_score

out_10 = score_dataframe(test_df, id_col=ID_COL, text_col=TEXT_COL, n_cases=10)
print("\nPreview (10 cases):")
print(out_10)

eval_10 = out_10.merge(
    test_df[[ID_COL, TARGET_COL]].head(10),
    on=ID_COL,
    how="inner"
).rename(columns={TARGET_COL: "gold"})

y_true_10 = eval_10["gold"].astype("Int64")
y_pred_10 = eval_10["gpt_score"].astype("Int64")

kappa_p_10 = cohen_kappa_score(y_true_10, y_pred_10)
print(f"Cohen's kappa (10 cases): {kappa_10:.3f}")

kappa_10 = cohen_kappa_score(y_true_10, y_pred_10, weights="quadratic")
print(f"Cohen's kappa (10 cases): {kappa_10:.3f}")

Preview (10 cases):
  essay_id_comp  gpt_score
0  7F220FD6CACF          1
1  B3FE48815543          2
2  B6428F6EB5F3          2
3  5D4E78CE6D5F          1
4  EA48C80121AD          1
5  CD8AAEA704AE          1
6  8119D80E030F          2
7  73E31A7D5720          1
8  56CA92EE1B0A          1
9  6C09B4AA6A77          1
Cohen's kappa (10 cases): 0.180
Cohen's kappa (10 cases): 0.390

In [57]:
# ===========================
# Full test set evaluation
# ===========================
out_test = score_dataframe(test_df, id_col=ID_COL, text_col=TEXT_COL)   # all rows
print("\nScored full test set")
print(out_test.head())
print(f"Total essays scored: {len(out_test)}")

eval_full = out_test.merge(
    test_df[[ID_COL, TARGET_COL, GROUP_COL]],
    on=ID_COL,
    how="inner"
).rename(columns={TARGET_COL: "y_true", "gpt_score": "y_pred_chatgpt"})

# Save full results (same style as BERT/TF-IDF)
preds_path = OUT_DIR / "scores_chatgpt_zeroshot.csv"
eval_full.to_csv(preds_path, index=False)
print(f"Saved full zeroshot results to {preds_path}")

# Compute Cohen's Kappa
from sklearn.metrics import cohen_kappa_score

y_true = eval_full["y_true"].astype("Int64")
y_pred = eval_full["y_pred_chatgpt"].astype("Int64")

kappa_plain = cohen_kappa_score(y_true, y_pred)
kappa_quad  = cohen_kappa_score(y_true, y_pred, weights="quadratic")

print("\n=== Evaluation on full test set ===")
print(f"Cohen's kappa (plain):     {kappa_plain:.3f}")
print(f"Cohen's kappa (quadratic): {kappa_quad:.3f}")

Scored full test set
  essay_id_comp  gpt_score
0  7F220FD6CACF          1
1  B3FE48815543          2
2  B6428F6EB5F3          2
3  5D4E78CE6D5F          1
4  EA48C80121AD          1
Total essays scored: 434
Saved full zeroshot results to outputs\scores_chatgpt_zeroshot.csv

=== Evaluation on full test set ===
Cohen's kappa (plain):     0.240
Cohen's kappa (quadratic): 0.369

In [ ]:
# # ===========================
# # ChatGPT Fewshots Scorer (1–3, score only, all rows)
# # ===========================


# OUT_DIR.mkdir(parents=True, exist_ok=True)  # reuse your OUT_DIR
# ORIG_LABEL_COL = "holistic_essay_score"     # original 1–6 labels for selecting examples

# # ---------------------------
# # Select 2 examples per new score: 
# #   new=1 <- orig {1,2}; new=2 <- orig {3,4}; new=3 <- orig {5,6}
# # ---------------------------
# def _pick_one(df: pd.DataFrame, seed: int) -> pd.Series | None:
#     if df.empty:
#         return None
#     rnd = random.Random(seed)
#     return df.sample(1, random_state=rnd.randint(0, 10**9)).iloc[0]

# def select_examples_two_per_newscore(train_df: pd.DataFrame, seed: int = 2025) -> pd.DataFrame:
#     pairs = {1: (1, 2), 2: (3, 4), 3: (5, 6)}
#     rows = []
#     for new_score, (o1, o2) in pairs.items():
#         r1 = _pick_one(train_df[train_df[ORIG_LABEL_COL] == o1], seed + new_score*10 + 1)
#         r2 = _pick_one(train_df[train_df[ORIG_LABEL_COL] == o2], seed + new_score*10 + 2)
#         for r in (r1, r2):
#             if r is not None:
#                 rows.append({
#                     "new_score": new_score,
#                     "orig_score": int(r[ORIG_LABEL_COL]),
#                     ID_COL: r[ID_COL],
#                     TEXT_COL: str(r[TEXT_COL]),
#                 })
#     ex_df = pd.DataFrame(rows).sort_values(["new_score", "orig_score"]).reset_index(drop=True)
#     ex_path = OUT_DIR / "chosen_examples_chatgpt_fewshot.csv"
#     ex_df.to_csv(ex_path, index=False)
#     print(f"Saved chosen examples → {ex_path}")
#     return ex_df

# # ---------------------------
# # Build SYSTEM message (same style as zero-shot + examples section)
# # ---------------------------
# def build_system_message_fewshot(examples_df: pd.DataFrame) -> str:
#     parts = [
#         # Keep wording consistent with zero-shot SYSTEM_MSG
#         "You are an essay rater following the Rubric. "
#         "Think step-by-step before deciding, and return the final score.\n\n"
#         "Rubric:\n",
#         RUBRIC_1_TO_3,
#         "\n\nReference examples with their final scores (1–3):"
#     ]
#     for _, r in examples_df.iterrows():
#         parts += [
#             f"\n=== EXAMPLE (final score {int(r['new_score'])}): ===\n\n",
#             r[TEXT_COL],
#             "\n\n"
#         ]
#     return "".join(parts)

# # ---------------------------
# # Few-shot scoring
# # ---------------------------
# def score_one_fewshot(essay_id: str, text: str, system_msg: str) -> int:
#     text = "" if text is None else str(text)
#     resp = client.chat.completions.create(
#         model=MODEL,
#         temperature=0,
#         max_tokens=32,
#         messages=[
#             {"role": "system", "content": system_msg},
#             {
#                 "role": "user",
#                 "content": (
#                     "Rate the following essay on the 1–3 rubric. "
#                     "Return only the final score.\n\n"
#                     f"ESSAY START:\n\n{text}\nESSAY END"
#                 )
#             },
#         ],
#         tools=TOOLS,
#         tool_choice={"type": "function", "function": {"name": "submit_score"}},
#     )
#     args = json.loads(resp.choices[0].message.tool_calls[0].function.arguments)
#     return int(args["score"])

# def score_dataframe_fewshot(df: pd.DataFrame, system_msg: str,
#                             id_col: str = ID_COL, text_col: str = TEXT_COL,
#                             n_cases: int | None = None) -> pd.DataFrame:
#     """
#     Score rows with few-shot prompting. Retries up to 3 times if score is missing.
#     """
#     df_use = df if n_cases is None else df.head(int(n_cases))
#     rows = []

#     for _, r in df_use.iterrows():
#         essay_id = str(r[id_col])
#         text = r[text_col]

#         score = None
#         for attempt in range(3):  # try up to 3 times
#             try:
#                 score = score_one_fewshot(essay_id, text, system_msg)
#             except Exception:
#                 score = None
#             if score is not None:
#                 break
#         if score is None:
#             print(f"⚠️ Warning: could not score essay_id={essay_id} after 3 attempts")

#         rows.append({id_col: essay_id, "gpt_score": score})

#     return pd.DataFrame(rows)

In [ ]:
# # ===========================
# # Example workflow (10-case sanity, then full set)
# # ===========================
# # 1) Build examples from TRAIN using original 1–6 labels
# examples_df = select_examples_two_per_newscore(train_df)

# # 2) Construct SYSTEM message (rubric + examples; same style as zero-shot)
# system_msg_few = build_system_message_fewshot(examples_df)


# print(system_msg_few)  # sanity check

Saved chosen examples → outputs\chosen_examples_chatgpt_fewshot.csv
You are an essay rater following the Rubric. Think step-by-step before deciding, and return the final score.

Rubric:
Holistic 1–3 scale for a source-based persuasive essay.

3: An essay in this category demonstrates clear and consistent mastery. It effectively develops a point of view with strong and accurate use of source evidence. The essay is well organized and focused, showing coherence and smooth progression of ideas. Language use is precise, varied, and appropriate, with meaningful sentence variety. Only minor or occasional errors may appear, but they do not interfere with meaning.

2: An essay in this category demonstrates adequate but uneven command. It develops a point of view and shows some critical thinking, though examples and evidence may be limited or inconsistently used. Organization is generally clear, but lapses in focus or coherence are present. Language is ordinary or inconsistent, sometimes weak or inappropriate in word choice, and sentence variety may be limited. Noticeable errors in grammar, usage, or mechanics occur, though meaning is still understandable overall.

1: An essay in this category demonstrates very limited or no mastery. The point of view may be vague, seriously limited, or entirely absent, with weak, irrelevant, or no use of evidence. The essay is disorganized or incoherent, with poor focus and progression of ideas. Vocabulary is very limited or incorrect, sentence structure is severely flawed, and pervasive errors in grammar, usage, or mechanics interfere with meaning.

Reference examples with their final scores (1–3):
=== EXAMPLE (final score 1): ===

I think yes, it can help students with their feeing becuase my first reason is becuase emotions matter alot. My seconed reason is becuase reason a article can halp people feel better if they pay good attions to what the story says. my last reason is becuase showing feelings they the way we look.

My first reason it can help students becuase by the way people read the story and look at the foto there is a lot of ways to look and read it. If there is a person who really is feeling sad they can read a story that has a lil og exititing moments on the story and with happy pictues that shows the feelings of the story. It can help alot beuase by looking at the pictuce and really paying attintion to the story it can grab the readers attintion. Once th author got the readers attiontion the reader is going to be focesed of what the book is about and going to make them change their feelings.

My seconed reason by reading the article it can change feelings. It can make then get into the feeling they want to get into eather it can be mad, sad, happy scared, exited, ect. There is a lot of feeling people can get into if they into what the author want to tell them by reading.

My last reason is by the way they look. Not alot of the people show they way they feel. If people dont show how they feel it becuase most of the idea is becuase hey are holding there feelings down deep in them. If they not showing it most people say they dont show it because they dont want to make people worry becuase they are in a bad mood and just dont want to get bothered. They try to show they are stong but deep dow they are holding a hard feelings they they going to remember at some other time becuase they are heoding it in them and they are the people who just dont want to do stuff at a surten time. The people who show there feeings i think they are the people who have the most good time becuase they get rid of that feeling.

Inconcluion that is my three reasons why it think it can help people when they are in the mood they dont want to be in.


=== EXAMPLE (final score 1): ===

Yes useing this new technology for facial action coding system can help identifing human emotions. Just like looking at a freiends face you can tell what they are feeling and how they are. Reading a person emotions can be helpful in most case seeing if they are having a good day or have a bad one or just a regular one. By looknig at a face can tell a whole lot about that perosn.

The system identifing your face just by the muscular parts moving. In pargraph 7 it tell's you to look in a mirror by raiseing your lips at corners of your mouth, then squint your eyes slightly, and holding that raise the outer parts of your cheeks up toward your eyes this shows you are happy. the process begins when the computer constructs a 3-D model of the faced and looking at all 44 major muscles. It has classified all 6 major emotions in a person/human happiness, suprise ,anger,disgust,fear, and sadness an associsated ech iwth the characteristic movements of the facial muscles.

This technology an aslo tell when a person is lieing there are muscles called orbiculais oculi pars palpabraeus that makes crows feet arounf your eyes but in a false smile the mouth is stretched sideways using the zygomatic witch is a major different muscle and to experts when a smiling politican or celebrity isn't being truthful.

Having this new techology in the world opens up lots of ne thing for reading a students or persons emotion they help with a lot of thing and reading the mona lisa smile or tell if she was not happy reading rach muscle was terific example on how this new system could work.


=== EXAMPLE (final score 2): ===

The value of using this technology to read students emotional expressions is an extremely smart idea. They see if they were confused or not. This software could help kids understand their assignments easier, explain more things throughly, and break the subject down into smaller sections.

The way that this software could help kids understand their assignments easier is that it could read their emotions while they're taking notes and the teacher says something they don't understand. The software could then read that emotion of confusion and show them a simplier way to understand it. Thus making the lesson easier to understand so they could actually do their work right instead of doing it completely wrong.

Another way that this software could help students understand things better is that it could explain more throughly. For example, a student could be sitting in math class and taking notes. The kid might not understand what the teacher means as he's talking about a specific formula. The software could reconigze the look and explain it better to the sudent so that they understand what they meant.

The last reason why this software could be useful is that it could break down in the lesson into smaller sections. A kid could be completely lost on what he's learning about in science and they're overwhelmed by everything together. The program could reconigze the confusion of the kid. It could then break the whole lesson apart and explain it one step at a time so could make more sense to them.

In conclusion, this software could do amazing things to help students understand and comprehend a lesson better than anything else. While this program will probably never be available for my education, it would be amazing asset for future students. The software could make it easier for assignments to be understood, explain a lesson further than the teacher did, and break lessons down into smaller sections. This software is the future for our world's education.


=== EXAMPLE (final score 2): ===

Are the students using the technology to read their emotional expressions? Is it good? Using the technology to read the emotional expressions of students in a classroom is valuable because some new computer software that can recognize emotions, technology can make a smile to our face, and students can relax their stress by using technology. If students uses technology, they can get a lot of benefits from it.

Some new computer software that can recognize emotions because everybody has their emotion like happiness, surprise, anger, disgust, fear, and sadness these are associated each with characteristic movements of the facial muscles. If students was so confused, their mind will not recognize on their homework. They cannot be focus their education and they don't know what did they learn, how to do their homework. Using by technology like a looking funny videos, they can recognize their emotions.

Technology can make a smile to our face because how much technology can do by playing games, looking funny videos, and like a using facebook. Imagine a computer that knows when youre happy or sad. For example, if you smile when a Web ad appears on your screen, a similar ad might follow. But if you frown, the next ad will be different. "A classroom computer could recognize when a student is becoming confused or bored." technology can make computer-animated faces more expressive for video games or video surgery that's why technology can make a smile to our face.

Students can relax their stress by using technology because when they were sad or confused, they can relax their stress on online. For example- playing video games, looking funny movies on facebook or youtube. So they would be laughing when they looked funny movies. If they want someting, the can buy that on the online shopping. It will be cool. Students have every classes' homework, sometimes they will bore and confuse if they don't know how to do it. So they can relax by using technology.

I agree students are using technology is great because it makes a smile on their faces. When they were bored or aloned, technology can makes a partner them. If students were seperated country each other, they can call video call and they can text messages by using technology texting apps so using technology is great. They can buy dresses, phones, makeup etc....by using technology that online shopping. They can play games and can watch funny movies when they were bored. Technology can help their mind will fresh and can make a smile on their face.


=== EXAMPLE (final score 3): ===

Imagine someone that is so familiar with a friend or loved one that they can tell what emotion they're feeling without having to say anything at all. Better yet, imagine if something was this smart. In the article, "Making Mona Lisa Smile," the author, Nick D'Alto, tells the readers about a new technology created to read the emotional cues from a human to further the communicable relationship between computers and humans alike. This technology, created by Professor Thomas Huang, "calculates" the emotions displayed on the face of the user of the computer, and was said to encourage learning and help the boredom and other emotions often felt by humans when learning. Later on in the article, D'Alto writes about how helpful this superior technology would be in the classroom and other learning environments, compared to the average computer used in schools all around the world. The technology described in the article, "Making Mona Lisa Smile," that reads the emotional expressions of students in a classroom is valuable to learners all over the world and should be used in modern-day schools.

The advanced technology recently created to read the emotions of the user, and impact the way they learn in the classroom is helpful and valuable. This is shown throughout the article by describing how the technology works and how it can be used to locate the emotions on the users' face. "Using video imagery, the new emotion-recognition software can track these facial movements- in a real face or in the painted face of Mona Lisa," (Paragraph 4). This quote describes to the reader the advancements of this technology, and just how unique the technology is in its intelligence. "Of course, most of us would have trouble actually describing each facial trait that conveys happy, worried, etc... His [Dr. Huang] new computer software stores similar anatomical information as electronic code," (Paragraph 5). This quote is helpful in giving the reader more information about how advanced this technology is, and how superior it is to even the skill of humans. Together, these quotes show that the technology would ultimately be more valuable in the classroom for the use of students.

One may even ask, "How would this technology helps students?" The answer to that very question lies in the article, "Making Mona Lisa Smile." This special software is very important to students because it could very well increase their chances of success in the classroom. "A classroom computer could recognize when a student is becoming confused or bored,' Dr. Huang predicts. 'Then it could modify the lesson, like an effective human instructor," (Paragraph 6). This quote gives the reader more information about how helpful this computer software could be in a learning environment, by being able to keep the learner's attention on the knowledge they are consuming. Another quote, from paragraph 6, "For example, if you smile when a Web ad appears on your screen, a similar ad will follow. But if you frown, the next ad will be different." This quote explains more examples of the skills of the computer technology, and gives the reader an idea about how students can use these basic, yet complicated tools to their advantage in the classroom.

This great technology can be so helpful to students, teachers, and employees in almost all kinds of learning environments by being able to give each and every person the best kind of learning session that they need. The technoloical devices at schools in this day and age just seem inferior to the kind of learning one can get via this advanced software created by Dr. Huang. "Your home PC can't handle the complex algorithms used to decode Mona Lisa's smile," (Paragraph 7). This quote shows evidence in the comparison between regular technology and the unique technology that is created for the use of learning in a classroom. Another quote from the article, "To an expert, faces don't lie; these muscles clues are sometimes used to spot when a "smiling" politician or celebrity isn't being truthful," (Paragraph 8), tells the readers that there are signs of false emotions and real emotions. These signs are easily caught by the technology software, and used to make learning easy and fun in the classroom, which can be extremely beneficial in the long run for school systems and teachers.

Technology these days can be used for both good or bad things, and often, technology is used for both. But a technology that is so helpful for learning and other school things is good, and needs to be used in order to improve a learning environment. The technology software that can read human emotion, and from there, improve the knowledge a student consumes is so very important and valuable. That's why this superior and advanced technology is valuable to students and school systems all over the world.


=== EXAMPLE (final score 3): ===

Emotions are a vital part of human life. Although they are sometimes overlooked or seem to not be present simply by looking at someone's face, they are used every day. The article "Making Mona Lisa Smile," introduces information regarding a technology which is able to detect the most common emotions. While this invention is widely seen as incredible, if not revolutionary, the Facial Action Coding System's presence is not valuable in classrooms.

The Facial Action Coding System does not have much value when it comes to using this technology to read students' emotinal expressions. The technology itself, while advanced in certain ways, is not that much more effective than a teacher's or students's abiltiy to distinguish feelings. The author, in his article presenting the many positives of this technology, addresses the idea that the system is able, from a 3D model it has built, to analyze the msucles of the face, matching their activity to certain basic emotions. The technology's ability to recognize emotions based on facial features and human behavior is something that humans have been doing automatically for centuries. The specific muscle structure is not necessary to determining one's feelings, as their use show noticeable changes on the face and are visible to the naked eye. Although this might be quicker, the technology would not have much value for classroom situations, as teachers could easily, while paying more attention to their students, notice the same details, identify changes in emotion, and alter their ways of teaching accordingly. Overall, the human's ability to identify basic emotional expressions would render this technology rather unvaluable in classrooms.

Similarly, the purely scientific origin of the Facial Action Coding System decreases the value this technological innovation would have for students in a classroom. While it might be successful in identifying the emotions of students, the Facial Action Coding System relies purely on the muscle behavior and structure, as mentioned in the article, meaning that no other factors would be taken into consideration. Many factors other than emotion, such as fatigue, can alter a student's appearance or behavior. The coding system would most likely, as a result of these underlying factors, as well as the very limited amount of emotions it can perceive, make the technolgy unvaluable when comes times to read student's emotional expressions. The generalization of emotions detected would produce false or unaccurate results, rendering the program useless in classrooms. The Facial Action Coding System, due to its computerized nature and lack of human perception, would not be a valuable addition to classrooms.

The lack of privacy this new technology brings makes the invention unvaluable. While some may think this to be a good way to improve student's lives throughout the school day, this facial recognition would raise many questions and controversy regarding student privacy. As the author states in the article, the Facial Action Coding System could be implemented in computers with the purpose of regulating ads and personalizing them to someone's preferences, likes, and dislikes. This is not only unnecessary, but would mean having a constant stream of visual information regarding students being sorted and analyzed. If this were implemented in classrooms, a number of parents and students alike would find this to be an intrusion of privacy, resulting in complaints, debates and overall unnecessary problems added to the education system. While this innovation might be somewhat useful or bring more attention to student's feelings, the excessive problems and controversy it would create makes the student emotional expression detector technology unvaluable and not a good addition to school.

The Facial Action Coding System is not valuable in reading the emotional expressions of students in a classroom. The technology, although it could properly analyze the muscles and facial structure of students in classrooms, could easily be matched by a teacher, does not take in all possible factors, and would conjure up many questions regarding privacy in schools. While this program would have little to no value in classes, it could provide help to investigative work. Emotions are extremely versatile and human expressions, although they share some similarities, widely vary based off of each person and circumstance.

In [ ]:
# # 3) Quick sanity (10 essays) + save + kappa
# out_10_fs = score_dataframe_fewshot(test_df, system_msg_few, id_col=ID_COL, text_col=TEXT_COL, n_cases=10)
# eval_10_fs = out_10_fs.merge(
#     test_df[[ID_COL, TARGET_COL, GROUP_COL]].head(10),
#     on=ID_COL, how="inner"
# ).rename(columns={TARGET_COL: "y_true", "gpt_score": "y_pred_chatgpt_fewshot"})

# preds_path_10 = OUT_DIR / "scores_chatgpt_fewshot_10.csv"
# eval_10_fs.to_csv(preds_path_10, index=False)
# print(f"Saved 10-case few-shot results → {preds_path_10}")

# y_true_10 = eval_10_fs["y_true"].astype("Int64")
# y_pred_10 = eval_10_fs["y_pred_chatgpt_fewshot"].astype("Int64")
# print(f"Kappa (10 cases, plain):     {cohen_kappa_score(y_true_10, y_pred_10):.3f}")
# print(f"Kappa (10 cases, quadratic): {cohen_kappa_score(y_true_10, y_pred_10, weights='quadratic'):.3f}")

Saved 10-case few-shot results → outputs\scores_chatgpt_fewshot_10.csv
Kappa (10 cases, plain):     0.388
Kappa (10 cases, quadratic): 0.483

In [ ]:
# # 4) Full test set + save + kappa
# out_full_fs = score_dataframe_fewshot(test_df, system_msg_few, id_col=ID_COL, text_col=TEXT_COL)
# eval_full_fs = out_full_fs.merge(
#     test_df[[ID_COL, TARGET_COL, GROUP_COL]],
#     on=ID_COL, how="inner"
# ).rename(columns={TARGET_COL: "y_true", "gpt_score": "y_pred_chatgpt_fewshot"})

# preds_path_full = OUT_DIR / "scores_chatgpt_fewshot.csv"
# eval_full_fs.to_csv(preds_path_full, index=False)
# print(f"Saved full few-shot results → {preds_path_full}")

# y_true = eval_full_fs["y_true"].astype("Int64")
# y_pred = eval_full_fs["y_pred_chatgpt_fewshot"].astype("Int64")
# print("\n=== Few-shot Evaluation on full test set ===")
# print(f"Cohen's kappa (plain):     {cohen_kappa_score(y_true, y_pred):.3f}")
# print(f"Cohen's kappa (quadratic): {cohen_kappa_score(y_true, y_pred, weights='quadratic'):.3f}")

PermissionError: [Errno 13] Permission denied: 'outputs\\scores_chatgpt_fewshot.csv'

In [ ]:
# preds_path_full = OUT_DIR / "scores_chatgpt_fewshot.csv"
# eval_full_fs.to_csv(preds_path_full, index=False)
# print(f"Saved full few-shot results → {preds_path_full}")

# y_true = eval_full_fs["y_true"].astype("Int64")
# y_pred = eval_full_fs["y_pred_chatgpt_fewshot"].astype("Int64")
# print("\n=== Few-shot Evaluation on full test set ===")
# print(f"Cohen's kappa (plain):     {cohen_kappa_score(y_true, y_pred):.3f}")
# print(f"Cohen's kappa (quadratic): {cohen_kappa_score(y_true, y_pred, weights='quadratic'):.3f}")

Saved full few-shot results → outputs\scores_chatgpt_fewshot.csv

=== Few-shot Evaluation on full test set ===
Cohen's kappa (plain):     0.451
Cohen's kappa (quadratic): 0.544

In [ ]:
# ===========================
# ChatGPT Fewshots Scorer v2 (1–3, score only, all rows)
# ===========================


OUT_DIR.mkdir(parents=True, exist_ok=True)  # reuse your OUT_DIR
ORIG_LABEL_COL = "holistic_essay_score"     # original 1–6 labels for selecting examples

# ---------------------------
# Select 2 examples per new score: 
#   new=1 <- orig {1,2}; new=2 <- orig {3,4}; new=3 <- orig {5,6}
# ---------------------------
def _pick_one(df: pd.DataFrame, seed: int) -> pd.Series | None:
    if df.empty:
        return None
    rnd = random.Random(seed)
    return df.sample(1, random_state=rnd.randint(0, 10**9)).iloc[0]

def select_examples_two_per_newscore(train_df: pd.DataFrame, seed: int = 2025) -> pd.DataFrame:
    pairs = {1: (1, 2), 2: (3, 4), 3: (5, 6)}
    rows = []
    for new_score, (o1, o2) in pairs.items():
        r1 = _pick_one(train_df[train_df[ORIG_LABEL_COL] == o1], seed + new_score*10 + 1)
        r2 = _pick_one(train_df[train_df[ORIG_LABEL_COL] == o2], seed + new_score*10 + 2)
        for r in (r1, r2):
            if r is not None:
                rows.append({
                    "new_score": new_score,
                    "orig_score": int(r[ORIG_LABEL_COL]),
                    ID_COL: r[ID_COL],
                    TEXT_COL: str(r[TEXT_COL]),
                })
    ex_df = pd.DataFrame(rows).sort_values(["new_score", "orig_score"]).reset_index(drop=True)
    ex_path = OUT_DIR / "chosen_examples_chatgpt_fewshot.csv"
    ex_df.to_csv(ex_path, index=False)
    print(f"Saved chosen examples → {ex_path}")
    return ex_df

# ---------------------------
# Build SYSTEM message (same style as zero-shot + examples section)
# ---------------------------
def build_system_message_fewshot(examples_df: pd.DataFrame) -> str:
    parts = [
        # Keep wording consistent with zero-shot SYSTEM_MSG
        "You are an essay rater following the Rubric. "
        "Think step-by-step before deciding, and return the final score.\n\n"
        "Rubric:\n",
        RUBRIC_1_TO_3]

# ---------------------------
# Few-shot scoring
# ---------------------------
def score_one_fewshot(essay_id: str, text: str, system_msg: str) -> int:
    text = "" if text is None else str(text)
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        max_tokens=32,
        messages=[
            {"role": "system", "content": SYSTEM_MSG},

            # Example 1
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 1]\nESSAY END"
            )},
            {"role": "assistant", "content": "1"},

            # Example 2
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 2]\nESSAY END"
            )},
            {"role": "assistant", "content": "1"},

            # Example 3
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 3]\nESSAY END"
            )},
            {"role": "assistant", "content": "2"},

            # Example 4
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 4]\nESSAY END"
            )},
            {"role": "assistant", "content": "2"},

            # Example 5
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 5]\nESSAY END"
            )},
            {"role": "assistant", "content": "3"},

            # Example 6
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                "ESSAY START:\n\n[EXAMPLE ESSAY TEXT 6]\nESSAY END"
            )},
            {"role": "assistant", "content": "3"},

            # Now the real input
            {"role": "user", "content": (
                "Rate the following essay on the 1–3 rubric. "
                "Return only the final score.\n\n"
                f"ESSAY START:\n\n{text}\nESSAY END"
            )},
        ],  

        tools=TOOLS,
        tool_choice={"type": "function", "function": {"name": "submit_score"}},
    )
    args = json.loads(resp.choices[0].message.tool_calls[0].function.arguments)
    return int(args["score"])


def score_dataframe_fewshot(df: pd.DataFrame, system_msg: str,
                            id_col: str = ID_COL, text_col: str = TEXT_COL,
                            n_cases: int | None = None) -> pd.DataFrame:
    """
    Score rows with few-shot prompting. Retries up to 3 times if score is missing.
    """
    df_use = df if n_cases is None else df.head(int(n_cases))
    rows = []

    for _, r in df_use.iterrows():
        essay_id = str(r[id_col])
        text = r[text_col]

        score = None
        for attempt in range(10):  # try up to 10 times
            try:
                score = score_one_fewshot(essay_id, text, system_msg)
            except Exception:
                score = None
            if score is not None:
                break
        if score is None:
            print(f"⚠️ Warning: could not score essay_id={essay_id} after 10 attempts")

        rows.append({id_col: essay_id, "gpt_score": score})

    return pd.DataFrame(rows)

In [74]:
# ---------------------------
# Build SYSTEM message (v2 = identical to zero-shot; no examples inside)
# ---------------------------
def build_system_message_fewshot(examples_df: pd.DataFrame) -> str:
    # v2: keep parity with zero-shot; examples will be injected as user/assistant turns
    return SYSTEM_MSG

# ===========================
# Example workflow (10-case sanity, then full set)
# ===========================
# 1) Build examples from TRAIN using original 1–6 labels
examples_df = select_examples_two_per_newscore(train_df, seed=2025)

# 2) Construct SYSTEM message (v2 = same as zero-shot)
system_msg_few = build_system_message_fewshot(examples_df)

print(system_msg_few)  # sanity check: should match SYSTEM_MSG verbatim

Saved chosen examples → outputs\chosen_examples_chatgpt_fewshot.csv
You are an essay rater following the Rubric. Think step-by-step before deciding, and return the final score.

Rubric:
Holistic 1–3 scale for a source-based persuasive essay.

3: An essay in this category demonstrates clear and consistent mastery. It effectively develops a point of view with strong and accurate use of source evidence. The essay is well organized and focused, showing coherence and smooth progression of ideas. Language use is precise, varied, and appropriate, with meaningful sentence variety. Only minor or occasional errors may appear, but they do not interfere with meaning.

2: An essay in this category demonstrates adequate but uneven command. It develops a point of view and shows some critical thinking, though examples and evidence may be limited or inconsistently used. Organization is generally clear, but lapses in focus or coherence are present. Language is ordinary or inconsistent, sometimes weak or inappropriate in word choice, and sentence variety may be limited. Noticeable errors in grammar, usage, or mechanics occur, though meaning is still understandable overall.

1: An essay in this category demonstrates very limited or no mastery. The point of view may be vague, seriously limited, or entirely absent, with weak, irrelevant, or no use of evidence. The essay is disorganized or incoherent, with poor focus and progression of ideas. Vocabulary is very limited or incorrect, sentence structure is severely flawed, and pervasive errors in grammar, usage, or mechanics interfere with meaning.

In [75]:
# 3) Quick sanity (10 essays) + save + kappa
out_10_fs = score_dataframe_fewshot(test_df, system_msg_few, id_col=ID_COL, text_col=TEXT_COL, n_cases=10)
eval_10_fs = out_10_fs.merge(
    test_df[[ID_COL, TARGET_COL, GROUP_COL]].head(10),
    on=ID_COL, how="inner"
).rename(columns={TARGET_COL: "y_true", "gpt_score": "y_pred_chatgpt_fewshot"})

preds_path_10 = OUT_DIR / "scores_chatgpt_fewshot_10.csv"
eval_10_fs.to_csv(preds_path_10, index=False)
print(f"Saved 10-case few-shot results → {preds_path_10}")

y_true_10 = eval_10_fs["y_true"].astype("Int64")
y_pred_10 = eval_10_fs["y_pred_chatgpt_fewshot"].astype("Int64")
print(f"Kappa (10 cases, plain):     {cohen_kappa_score(y_true_10, y_pred_10):.3f}")
print(f"Kappa (10 cases, quadratic): {cohen_kappa_score(y_true_10, y_pred_10, weights='quadratic'):.3f}")

Saved 10-case few-shot results → outputs\scores_chatgpt_fewshot_10.csv
Kappa (10 cases, plain):     0.615
Kappa (10 cases, quadratic): 0.688

In [76]:
# 4) Full test set + save + kappa
out_full_fs = score_dataframe_fewshot(test_df, system_msg_few, id_col=ID_COL, text_col=TEXT_COL)
eval_full_fs = out_full_fs.merge(
    test_df[[ID_COL, TARGET_COL, GROUP_COL]],
    on=ID_COL, how="inner"
).rename(columns={TARGET_COL: "y_true", "gpt_score": "y_pred_chatgpt_fewshot"})

preds_path_full = OUT_DIR / "scores_chatgpt_fewshot.csv"
eval_full_fs.to_csv(preds_path_full, index=False)
print(f"Saved full few-shot results → {preds_path_full}")

y_true = eval_full_fs["y_true"].astype("Int64")
y_pred = eval_full_fs["y_pred_chatgpt_fewshot"].astype("Int64")
print("\n=== Few-shot Evaluation on full test set ===")
print(f"Cohen's kappa (plain):     {cohen_kappa_score(y_true, y_pred):.3f}")
print(f"Cohen's kappa (quadratic): {cohen_kappa_score(y_true, y_pred, weights='quadratic'):.3f}")

Saved full few-shot results → outputs\scores_chatgpt_fewshot.csv

=== Few-shot Evaluation on full test set ===
Cohen's kappa (plain):     0.401
Cohen's kappa (quadratic): 0.516

In [ ]:
# y_true = eval_full_fs["y_true"].astype("Int64")
# y_pred = eval_full_fs["y_pred_chatgpt_fewshot"].astype("Int64")

# # Drop rows with NA in either column
# mask = ~(y_true.isna() | y_pred.isna())
# y_true = y_true[mask]
# y_pred = y_pred[mask]

# print("\n=== Few-shot Evaluation on full test set ===")
# print(f"Cohen's kappa (plain):     {cohen_kappa_score(y_true, y_pred):.3f}")
# print(f"Cohen's kappa (quadratic): {cohen_kappa_score(y_true, y_pred, weights='quadratic'):.3f}")

=== Few-shot Evaluation on full test set ===
Cohen's kappa (plain):     0.401
Cohen's kappa (quadratic): 0.516